# Generated by Django 4.1.4 on 2023-02-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('filepath', models.ImageField(blank=True, default=None, max_length=255, upload_to='media/data')),
            ],
        ),
        migrations.CreateModel(
            name='DataAPI',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=None, null=True)),
                ('admin_id', models.IntegerField(default=None)),
                ('deliverer_id', models.IntegerField(default=None, null=True)),
                ('returned_items', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('refund', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('items_count', models.IntegerField(default=0)),
                ('destination', models.CharField(default=None, max_length=255)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('has_discount', models.IntegerField(default=0, null=True)),
                ('is_poked', models.IntegerField(default=0)),
                ('receipt', models.CharField(default=None, max_length=255)),
                ('amount', models.IntegerField(default=None)),
                ('total_buying_price', models.IntegerField(default=0)),
                ('is_paid', models.IntegerField(default=None)),
                ('transaction_id', models.IntegerField(default=None, null=True)),
                ('selcom_order', models.CharField(default=None, max_length=255, null=True)),
                ('invoice_number', models.CharField(default=None, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(default=None)),
                ('is_processed', models.IntegerField(default=None)),
                ('is_informed', models.IntegerField(default=0)),
                ('notification_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='Unpaid', max_length=255)),
                ('is_received', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(default=None)),
                ('tagname', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inference_label', models.IntegerField(default=0)),
                ('inference_text', models.TextField(blank=True, max_length=200)),
                ('inference_results', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
