# Generated by Django 4.1.4 on 2023-02-02 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataapi',
            name='processed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dataapi',
            name='receipt',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
