# Generated by Django 4.1.4 on 2023-02-02 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_inference_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataapi',
            name='processed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
