# Generated by Django 4.1.4 on 2023-02-02 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_dataapi_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataapi',
            name='processed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
